#!/bin/bash
#
# Display the content of the primary selection (clipboard) as a QR code.
# Especially useful for URLs.
# Needs xsel/wl-paste, qrencode and imv.

img=$(mktemp --suffix=.png)
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    wl-paste -p | qrencode -o "$img"
else
    xsel -p | qrencode -o "$img"
fi

imv "$img"
rm "$img"
